version: '3.7'
services:
  message_db:
    build:
      args:
        MESSAGE_DB_VERSION: ${MESSAGE_DB_VERSION:-1.2.6}
      context: .
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432'
